# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Arda Senocak
name: Arda Senocak
position: Postdoctoral Research Associate
email: arda.senocak@gmail.com
# description: >-
description: | 
  I am an Assistant Professor in the Graduate School of Artificial Intelligence and the Department of Computer Science and Engineering at UNIST.
  
  Before joining UNIST, I spent three wonderful years at the Multimodal AI Lab at KAIST. From 2022 to 2025, I was a Postdoctoral Researcher in the School of Electrical Engineering at KAIST, working with Prof. Joon Son Chung. I later worked as a Research Assistant Professor in the same department.
  
  I earned both my Ph.D. and M.S. degrees from the School of Electrical Engineering at KAIST under the supervision of Prof. In So Kweon, and received my B.S. degree in Computer Science, also from KAIST.

  My research focuses on multimodal learning, particularly on developing machine perception models that can learn from visual, auditory, and other sensory inputs to effectively interact with the world around them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ardasnck.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ardasnck
github_username: ardasnck
google_scholar: ivZrAU0AAAAJ
# google_analytics: -

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
